# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
source 'git@gitlab.oneitfarm.com:SpecPods/CIRouter.git'

target '__ProjectName__' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!
  pod 'RxSwift','3.6.1'
  pod 'RxCocoa','3.6.1'
  pod 'RxDataSources','1.0.4'
  pod 'CIRouter','0.0.1'
  pod 'Then','2.1.0'
  pod 'SnapKit','3.2.0'
  pod 'SwiftLint','0.21.0'
  pod 'RxOptional','3.1.3'
  pod 'RxBlocking','3.6.1'
end
